### ISSUE TITLE
running quickstart.sh in Windows

### ISSUE THREAD

**Issue by RasonJ** [o19s/chorus-opensearch-edition#1]
Running the `quickstart.sh` in Windows WSL could give the following errors:
![image](https://github.com/o19s/chorus-opensearch-edition/assets/145287540/ef0c84cc-a9bf-47c6-9d73-9ca145fd5b6b)

To overcome this error, I ran the following two commands:
```unix
sudo apt-get update
sudo apt-get install dos2unix
```
Note, at least for me, it only worked with the Ubuntu distro and not the Debian distro.

Then you should be able to run `source quickstart.sh`; however, I then recieved Docker WSL errors (probably some faulty config on my side).  So, back in the Windows terminal I had to manually run:
 `docker compose up`

**Comment by epugh** [comment]
It would be nice if this was in the README for the next person ;-).    Honestly, I am floored that this ran on Windows, amazing!

**Comment by RasonJ** [comment]
Still working through issues, but really it's running in Docker on Windows.  The problem is that the shell scripts do some prep work.  Windows' wsl will run those scripts, but github converts the shell scripts adding \r's

**Comment by RasonJ** [comment]
I'll add a readme if we figure it all out

**Comment by epugh** [comment]
Did we get this to done?   Or do we need some pairing time...

**Comment by epugh** [comment]
This is a duplication of #10 in this repo....
