### ISSUE TITLE
Challenges running Chorus 000 Kata

### ISSUE THREAD

**Issue by Franborat** [o19s/chorus-opensearch-edition#128]
First of all, very cool project, thanks!

I'm trying to run Chorus, but got stucked. I first tried the 000 Kata, in here, running the transform_data.py results in an error "ModuleNotFoundError: No module named 'tqdm'", which I fixed by changing the command to:

`docker run -v "$(pwd)":/app -w /app python:3 sh -c "pip install tqdm && python3 ./opensearch/transform_data.py icecat-products-w_price-19k-20201127.json transformed_data.json"`

But I then get this other error in the script: 
File "/app/./opensearch/transform_data.py", line 27, in <module>
    json_obj.get('locale') == "us" and
    ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

I also tried to run the 000 Kata directly with **./quickstart.sh** but then I get:
Connecting to esci-s.s3.amazonaws.com (esci-s.s3.amazonaws.com)|16.15.184.159|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-11-28 16:49:11 ERROR 403: Forbidden.

Can I get some help to overcome this? I'd really like to test this out.

**Comment by wrigleyDan** [comment]
Hi @Franborat,

we recently switched to an alternative dataset and that causes the first Kata to be outdated. Sorry for that. This needs updating.

Apparently the dataset we use was temporarily not available. To me it looks like it is available again now. So running the `quickstart.sh` script should work again. Can you give that another try and give feedback if that's resolved?

Thanks!

**Comment by wrigleyDan** [comment]
Thanks for confirming that it works now!

The frontend is very basic at the moment, you are absolutely right: we only have a search bar and two filters (a brand filter and a product type filter). 
The algorithm picker will work once we merge #127 into main. With that a user can switch between keyword, neural search and hybrid search.
Is that what you meant with "not fully coded" or did I misunderstand you there?

So we have very basic functionality but the frontend could definitely do with some improvements, so if you want to contribute that would be awesome! Is there anything in particular that you were thinking of?

**Comment by Franborat** [comment]
Oh! I realized that the front-end was not loading well on my side. I now can see the filtering by brands and by product types, as well as the add to cart - before idk why it was not loading and that's why I thought the front-end was on the process of being built. 

I'll be doing the the Katas and getting familiarized with the project, which overall looks very cool. 

Thank you!

**Comment by wrigleyDan** [comment]
Sounds great!

We just merged #127 into main which has some improvements, so I recommend you pull the latest version and maybe start fresh.

I'll close this issue for now since you overcame the quickstart.sh issue. Feel free to open issues as you see them rising. And of course feel free to open PRs with improvements :)

Thanks for checking out Chorus!

**Comment by wrigleyDan** [comment]
closing this one
