### ISSUE TITLE
Create example middle layer service

### ISSUE THREAD

**Issue by jzonthemtn** [o19s/chorus-opensearch-edition#87]
Create example middle layer service. The service should serve as a proxy for the OpenSearch API. The service should accept query requests from clients, receive the query responses from OpenSearch, and cache the data, and remove specific data from the query responses prior to returning the response to the client.

When the event is sent to OpenSearch, it should traverse the middle layer service and be enriched with the cached data.

![image](https://github.com/o19s/chorus-opensearch-edition/assets/13176962/d0c31ca6-4ff0-406b-9e05-ff356b27e842)

**Comment by epugh** [comment]
@jzonthemtn remind me where the Go code is and where we are on this?

**Comment by jzonthemtn** [comment]
This was mostly merged in https://github.com/o19s/chorus-opensearch-edition/pull/104.

**Comment by epugh** [comment]
The remaining couple of "todo's" we'll cover elsewhere.   We now have the example, and can start writing up the docs for the workshop.
