### ISSUE TITLE
Demo: Eliminate quickstart.sh from Chorus docker demo

### ISSUE THREAD

**Issue by jzonthemtn** [o19s/chorus-opensearch-edition#9]
Move quickstart.sh functionality to docker compose

Recreated from https://github.com/o19s/opensearch-ubl/issues/33

**Comment by epugh** [comment]
@RasonJ I can pick this up, if you want to walk me through a bit what is working for you and what isn't...

**Comment by RasonJ** [comment]
So, generally shell scripts don't run on Windows :)
The easiest solution would be to move the quickstart.sh inside a container that already is running linux.

The more painful solution would be to pull out each piece of functionality in the quickstart.sh and translate it into docker compose commands.
Notable items:
- the first few lines just make sure that the proper unix commands exist.  In my WSL, I had to do an apt-get for each of these utilities.
![image](https://github.com/o19s/chorus-opensearch-edition/assets/145287540/1e75a155-40cd-4205-9be9-f7b467781101)

- all of the docker commands work pretty well on Windows; so, something like `docker compose up` runs natively on windows and doesn't need to be in the quickstart.sh.  So, the following is unnecessary.  (also, note that's how one _could_ init the `.ubi_log_events` store)
![image](https://github.com/o19s/chorus-opensearch-edition/assets/145287540/00f2cb77-2b9d-4b27-a581-d1e2aef79bb6)

- all curl commands can be run within the container.  i.e.:
![image](https://github.com/o19s/chorus-opensearch-edition/assets/145287540/d81b305f-ac09-4109-98bd-f88d16114b7e)

- I'd prefer us to simplify how the data is indexed.  For example, do we have to download the catalog each time?  Can we store the intermediate file `transformed_data.json` in some sort of artifactory/repo, and have the script just download that to index?
![image](https://github.com/o19s/chorus-opensearch-edition/assets/145287540/d6833f17-31d9-4f4e-b04e-4257756a1467)

**Comment by epugh** [comment]
Let's put this on hold for now....
